services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: studyhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/studyhub
      JWT_SECRET: change-me
      OPENWEATHER_KEY: ""
      NODE_ENV: development
    depends_on: [db]
    ports: ["8080:8080"]
  web:
    build: ./web
    depends_on: [api]
    ports: ["5173:80"]
volumes: { dbdata: {} }
