import { Router } from 'express';
import { authGuard } from '../../middlewares/authGuard';
import * as ctrl from './task.controller';
const r = Router();
r.use(authGuard);
r.get('/', ctrl.list);
r.post('/', ctrl.create);
r.put('/:id', ctrl.update);
r.delete('/:id', ctrl.remove);
export default r;
